### ISSUE TITLE
Hero text slips out of place in small browser sizes

### ISSUE THREAD

**Issue by cbirkholz** [godaddy/wp-uptown-style-theme#22]
I'm having an issue where text in the hero section slides out of center on smaller browser sizes, like mobile.
![heroissue](https://cloud.githubusercontent.com/assets/22947166/19541545/bb0c8ff8-962c-11e6-8096-89ae0b0c9911.png)
![heroissue2](https://cloud.githubusercontent.com/assets/22947166/19541544/bb0b8054-962c-11e6-92ad-57550063722b.png)

**Comment by EvanHerman** [comment]
Hi @cbirkholz 

I just did some testing on my end with the latest version here on GitHub. I'm not seeing the issue on my end.

What is the markup that you are using inside of the widget?

Here is the output on my end:

**Example:**
![Example](https://cldup.com/UG3uPs32cX.png)


Evan

**Comment by EvanHerman** [comment]
@cbirkholz If you are still encountering issue feel free to comment back here and we'll take a deeper look.
