### ISSUE TITLE
issue with header image and navigation bar- DUPLICATES can't remove!

### ISSUE THREAD

**Issue by fary6** [godaddy/wp-uptown-style-theme#32]
all of a sudden my header image and navigation bar both being duplicated on all pages. I cannot seem to remove the duplicates. Help!! how do i resolve this?? 

see attached.. this is the case for ALL pages 

![screen shot 2017-08-11 at 5 31 20 pm](https://user-images.githubusercontent.com/30941962/29236095-f739c5dc-7eba-11e7-977d-02e06ea540e2.png)

**Comment by fjarrett** [comment]
Hi @fary6 - I've never seen anything like this before, nor has anyone reported it, so thank you! Have you tried deactivating your plugins one-by-one to see if any of them are the culprit?

**Comment by EvanHerman** [comment]
Hi @fary6 

Are you still encountering this issue? If so, please feel free to reach out here and let us know. I will leave this open for a few more days then close it out.

Evan

**Comment by Aztriks** [comment]
I am having this same issue! It's very frustrating.

**Comment by ananasvis** [comment]
I have the same issue as well, did anyone figure it out?

**Comment by ananasvis** [comment]
nvmd just had to update the parent theme "primer"

**Comment by EvanHerman** [comment]
Closing this issue as it appears to be related to having an older version of the parent theme, Primer.
