### ISSUE TITLE
Unable to change the blog post title in uptown style theme

### ISSUE THREAD

**Issue by rabiyakhan9421** [godaddy/wp-uptown-style-theme#36]
I am unable to change the blog post title in the uptown theme. It is just shows "Posts" instead of the title.

**Comment by EvanHerman** [comment]
Hi @rabiyakhan9421 

Do you have a link to that page? I can do some testing to see if I can replicate the issue.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
