### ISSUE TITLE
Featured Images (Not Displaying)

### ISSUE THREAD

**Issue by WPNewbie88** [godaddy/wp-uptown-style-theme#48]
Hello,

I am currently trying to build my website using this theme. For some reason,  the "Featured Images" are not displaying on the website. I've tried re-installing the theme through c-panel but that doesn't seem to work. If anyone has any suggestions on what I can do to get those to appear, it would be greatly appreciated!

Thank you!

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
